Add regression test for #514
failures (2):

---- issue514::no_mismatch stdout ----
thread 'issue514::no_mismatch' panicked at 'called `Result::unwrap()` on an `Err` value: EndEventMismatch { expected: "html", found: "some-tag" }', tests\issues.rs:34:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- issue514::mismatch stdout ----
thread 'issue514::mismatch' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<html
>some-tag

', tests\issues.rs:59:17