Add regression test for #580
---- issue580 stdout ----
thread 'issue580' panicked at tests/serde-issues.rs:412:10:
called `Result::unwrap()` on an `Err` value: Custom("invalid length 0, expected tuple struct Wrapper with 1 element")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    issue580